In [2]:
import pandas as pd
import numpy as np


raw_train = pd.read_csv("data/car_breakdown_train.tsv", sep='\t')
raw_test = pd.read_csv("data/car_breakdown_test.tsv", sep="\t")
raw_truth = pd.read_csv("data/car_breakdown_test_truth.tsv", sep="\t")

In [3]:
raw_train.head()

,vehicleId,days,ecoMode,cityMode,sportMode,s1,s2,s3,s4,s5,...,s12,s13,s14,s15,s16,s17,s18,s19,s20,s21
0,1,1,-0.0007,-0.0004,100,518.67,641.82,1589.70,1400.60,14.62,...,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100,39.06,23.4190
1,1,2,0.0019,-0.0003,100,518.67,642.15,1591.82,1403.14,14.62,...,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100,39.00,23.4236
2,1,3,-0.0043,0.0003,100,518.67,642.35,1587.99,1404.20,14.62,...,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100,38.95,23.3442
3,1,4,0.0007,0.0000,100,518.67,642.35,1582.79,1401.87,14.62,...,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100,38.88,23.3739
4,1,5,-0.0019,-0.0002,100,518.67,642.37,1582.85,1406.22,14.62,...,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100,38.90,23.4044

In [4]:
raw_train.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
vehicleId,20631.0,51.506568,2.922763e+01,1.0000,26.0000,52.0000,77.0000,100.0000
days,20631.0,108.807862,6.888099e+01,1.0000,52.0000,104.0000,156.0000,362.0000
ecoMode,20631.0,-0.000009,2.187313e-03,-0.0087,-0.0015,0.0000,0.0015,0.0087
cityMode,20631.0,0.000002,2.930621e-04,-0.0006,-0.0002,0.0000,0.0003,0.0006
sportMode,20631.0,100.000000,0.000000e+00,100.0000,100.0000,100.0000,100.0000,100.0000
s1,20631.0,518.670000,0.000000e+00,518.6700,518.6700,518.6700,518.6700,518.6700
s2,20631.0,642.680934,5.000533e-01,641.2100,642.3250,642.6400,643.0000,644.5300
s3,20631.0,1590.523119,6.131150e+00,1571.0400,1586.2600,1590.1000,1594.3800,1616.9100
s4,20631.0,1408.933782,9.000605e+00,1382.2500,1402.3600,1408.0400,1414.5550,1441.4900
s5,20631.0,14.620000,1.776400e-15,14.6200,14.6200,14.6200,14.6200,14.6200
s6,20631.0,21.609803,1.388985e-03,21.6000,21.6100,21.6100,21.6100,21.6100
s7,20631.0,553.367711,8.850923e-01,549.8500,552.8100,553.4400,554.0100,556.0600
s8,20631.0,2388.096652,7.098548e-02,2387.9000,2388.0500,2388.0900,2388.1400,2388.5600
s9,20631.0,9065.242941,2.208288e+01,9021.7300,9053.1000,9060.6600,9069.4200,9244.5900
s10,20631.0,1.300000,0.000000e+00,1.3000,1.3000,1.3000,1.3000,1.3000
s11,20631.0,47.541168,2.670874e-01,46.8500,47.3500,47.5100,47.7000,48.5300
s12,20631.0,521.413470,7.375534e-01,518.6900,520.9600,521.4800,521.9500,523.3800
s13,20631.0,2388.096152,7.191892e-02,2387.8800,2388.0400,2388.0900,2388.1400,2388.5600
s14,20631.0,8143.752722,1.907618e+01,8099.9400,8133.2450,8140.5400,8148.3100,8293.7200
s15,20631.0,8.442146,3.750504e-02,8.3249,8.4149,8.4389,8.4656,8.5848
s16,20631.0,0.030000,1.387812e-17,0.0300,0.0300,0.0300,0.0300,0.0300
s17,20631.0,393.210654,1.548763e+00,388.0000,392.0000,393.0000,394.0000,400.0000
s18,20631.0,2388.000000,0.000000e+00,2388.0000,2388.0000,2388.0000,2388.0000,2388.0000
s19,20631.0,100.000000,0.000000e+00,100.0000,100.0000,100.0000,100.0000,100.0000
s20,20631.0,38.816271,1.807464e-01,38.1400,38.7000,38.8300,38.9500,39.4300
s21,20631.0,23.289705,1.082509e-01,22.8942,23.2218,23.2979,23.3668,23.6184

From the distribution of features, dropping features with no variance

In [5]:
drop_cols = ['sportMode', 's1', 's5', 's10', 's16', 's18', 's19']
features_col_name = raw_train.columns.drop(drop_cols).drop(["vehicleId", "days"])

raw_train.drop(drop_cols, axis=1, inplace=True)
raw_test.drop(drop_cols, axis=1, inplace=True)

In [6]:
raw_train.head()

,vehicleId,days,ecoMode,cityMode,s2,s3,s4,s6,s7,s8,s9,s11,s12,s13,s14,s15,s17,s20,s21
0,1,1,-0.0007,-0.0004,641.82,1589.70,1400.60,21.61,554.36,2388.06,9046.19,47.47,521.66,2388.02,8138.62,8.4195,392,39.06,23.4190
1,1,2,0.0019,-0.0003,642.15,1591.82,1403.14,21.61,553.75,2388.04,9044.07,47.49,522.28,2388.07,8131.49,8.4318,392,39.00,23.4236
2,1,3,-0.0043,0.0003,642.35,1587.99,1404.20,21.61,554.26,2388.08,9052.94,47.27,522.42,2388.03,8133.23,8.4178,390,38.95,23.3442
3,1,4,0.0007,0.0000,642.35,1582.79,1401.87,21.61,554.45,2388.11,9049.48,47.13,522.86,2388.08,8133.83,8.3682,392,38.88,23.3739
4,1,5,-0.0019,-0.0002,642.37,1582.85,1406.22,21.61,554.00,2388.06,9055.15,47.28,522.19,2388.04,8133.80,8.4294,393,38.90,23.4044

In [7]:
raw_test.head()

,vehicleId,days,ecoMode,cityMode,s2,s3,s4,s6,s7,s8,s9,s11,s12,s13,s14,s15,s17,s20,s21
0,1,1,0.0023,0.0003,643.02,1585.29,1398.21,21.61,553.90,2388.04,9050.17,47.20,521.72,2388.03,8125.55,8.4052,392,38.86,23.3735
1,1,2,-0.0027,-0.0003,641.71,1588.45,1395.42,21.61,554.85,2388.01,9054.42,47.50,522.16,2388.06,8139.62,8.3803,393,39.02,23.3916
2,1,3,0.0003,0.0001,642.46,1586.94,1401.34,21.61,554.11,2388.05,9056.96,47.50,521.97,2388.03,8130.10,8.4441,393,39.08,23.4166
3,1,4,0.0042,0.0000,642.44,1584.12,1406.42,21.61,554.07,2388.03,9045.29,47.28,521.38,2388.05,8132.90,8.3917,391,39.00,23.3737
4,1,5,0.0014,0.0000,642.51,1587.19,1401.92,21.61,554.16,2388.01,9044.55,47.31,522.15,2388.03,8129.54,8.4031,390,38.99,23.4130

In [8]:
rul_test = pd.DataFrame(raw_test.groupby('vehicleId')['days'].max()).reset_index()
rul_test.columns = ['vehicleId', 'max']
rul_test.head()

raw_truth['rtf'] = raw_truth['RUL'] + rul_test['max']
raw_truth.head()


raw_truth.drop('RUL', axis=1, inplace=True)
raw_test = raw_test.merge(raw_truth, on=['vehicleId'], how='inner')
raw_test['ttf'] = raw_test['rtf'] - raw_test['days']
raw_test.drop('rtf', axis=1, inplace=True)
raw_test.head()


raw_train['ttf'] = raw_train.groupby(['vehicleId'])['days'].transform(max) - raw_train['days']
raw_train.head()

test_df = raw_test.copy()
train_df = raw_train.copy()

In [9]:
window = 30

train_df['label'] = train_df['ttf'].apply(lambda x: 1 if x <= window else 0)
test_df['label'] = test_df['ttf'].apply(lambda x: 1 if x <= window else 0)

target_col_name = 'label'

seq_size = 60
seq_cols = features_col_name
nb_features = len(seq_cols)
batch_size = 256

In [10]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

train_df[features_col_name] = scaler.fit_transform(train_df[features_col_name])
test_df[features_col_name] = scaler.transform(test_df[features_col_name])

In [11]:
def generate_ts(id_df, seq_length, seq_cols):
    df_zeros = pd.DataFrame(np.zeros((seq_length-1, id_df.shape[1])), columns=id_df.columns)
    id_df = df_zeros.append(id_df, ignore_index=True)
    data_array = id_df[seq_cols].values
    num_elements = data_array.shape[0]
    ts_array = []
    for start, stop in zip(range(0, num_elements-seq_length), range(seq_length, num_elements)):
        ts_array.append(data_array[start:stop, :])
    return np.array(ts_array)


def generate_ts_label(id_df, seq_length, seq_cols, label_col):
    df_zeros = pd.DataFrame(np.zeros((seq_length-1, id_df.shape[1])), columns=id_df.columns)
    id_df = df_zeros.append(id_df, ignore_index=True)
    data_array = id_df[seq_cols].values
    num_elements = data_array.shape[0]
    label = []
    for start, stop in zip(range(0, num_elements-seq_length), range(seq_length, num_elements)):
        label.append(id_df[label_col][stop])
    return np.array(label)

In [12]:
x_train = np.concatenate(list(list(generate_ts(train_df[train_df['vehicleId'] == id],
                                               seq_size, seq_cols)) for id in train_df['vehicleId'].unique()))
y_train = np.concatenate(list(list(generate_ts_label(train_df[train_df['vehicleId'] == id],
                                                     seq_size, seq_cols, "label")) for id in train_df['vehicleId'].unique()))
x_test = np.concatenate(list(list(generate_ts(test_df[test_df['vehicleId'] == id],
                                              seq_size, seq_cols)) for id in test_df['vehicleId'].unique()))
y_test = np.concatenate(list(list(generate_ts_label(test_df[test_df['vehicleId'] == id],
                                                    seq_size, seq_cols, "label")) for id in test_df['vehicleId'].unique()))

In [13]:
def focal_loss(y_true, y_pred):
    gamma = 5.0
    alpha = 0.25
    pt_1 = tf.where(tf.equal(y_true, 1), y_pred, tf.ones_like(y_pred))
    pt_0 = tf.where(tf.equal(y_true, 0), y_pred, tf.zeros_like(y_pred))
    return -K.sum(alpha * K.pow(1. - pt_1, gamma) * K.log(pt_1)) - K.sum(
        (1 - alpha) * K.pow(pt_0, gamma) * K.log(1. - pt_0))


def f1(y_true, y_pred):
    def recall(y_true, y_pred):
        true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
        possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
        recall = true_positives / (possible_positives + K.epsilon())
        return recall

    def precision(y_true, y_pred):
        true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
        predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
        precision = true_positives / (predicted_positives + K.epsilon())
        return precision

    precision = precision(y_true, y_pred)
    recall = recall(y_true, y_pred)
    return 2 * ((precision * recall) / (precision + recall + K.epsilon()))

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score
from keras.models import Sequential
from keras.layers import Dense, Dropout, LSTM
from keras.callbacks import EarlyStopping
from keras.layers import Dense, Input, Conv1D, MaxPooling1D, LSTM, Flatten

Using TensorFlow backend.
/Users/danishkalim/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/danishkalim/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/danishkalim/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/danishkalim/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/danishkalim/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Users/danishkalim/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/Users/danishkalim/anaconda3/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/Users/danishkalim/anaconda3/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/Users/danishkalim/anaconda3/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/Users/danishkalim/anaconda3/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/Users/danishkalim/anaconda3/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/Users/danishkalim/anaconda3/lib/python3.6/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

In [15]:
def make_model():
    model = Sequential()
    model.add(Conv1D(35, kernel_size=3, input_shape=(seq_size, nb_features)))
    model.add(MaxPooling1D(pool_size=2))
    model.add(Conv1D(20, kernel_size=3))
    model.add(MaxPooling1D(pool_size=2))
    model.add(Flatten())
    model.add(Dense(30, activation="relu"))    
    model.add(Dense(1, activation="sigmoid"))
    return model

model = make_model()

WARNING:tensorflow:From /Users/danishkalim/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py:4070: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

In [16]:
model.compile(loss=focal_loss, optimizer='adam', metrics=['accuracy', f1])

model.summary()

model.fit(x_train, y_train, epochs=20, batch_size=batch_size, validation_split=0.4, verbose=1,
          callbacks=[EarlyStopping(monitor='val_loss', min_delta=0, patience=5, verbose=0, mode='auto')])

NameError: name 'K' is not defined

In [316]:
train_scores = model.evaluate(x_train, y_train, verbose=1, batch_size=batch_size)
y_prediction_train = model.predict_classes(x_train)

print('Train Accuracy: {}'.format(train_scores[1]))
print('Train F1: {}'.format(train_scores[2]))
print('Train Confusion Matrix: \n',confusion_matrix(y_train,y_prediction_train))



test_scores = model.evaluate(x_test, y_test, verbose=1, batch_size=batch_size)
y_prediction_test = model.predict_classes(x_test)

print('Test Accuracy: {}'.format(test_scores[1]))
print('Test F1: {}'.format(test_scores[2]))
print('Test Confusion Matrix: \n',confusion_matrix(y_test,y_prediction_test))

20531/20531 [==============================] - 0s 16us/step
Train Accuracy: 0.9813452959060669
Train F1: 0.9054272770881653
Train Confusion Matrix:
 [[17249   182]
 [  201  2899]]
12996/12996 [==============================] - 0s 17us/step
Test Accuracy: 0.9914588928222656
Test F1: 0.277495414018631
Test Confusion Matrix:
 [[12630    34]
 [   77   255]]